AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: AppSync API with Lambda Resolver example
Resources:
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: MyAppSyncUserPool
      Schema:
        - AttributeDataType: String
          Mutable: true
          Name: email
          Required: true

  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: MyAppSyncUserPoolClient
      GenerateSecret: false
      UserPoolId: !Ref CognitoUserPool

  AppSyncApi:
    Type: AWS::AppSync::GraphQLApi
    Properties:
      Name: MyAppSyncApi
      AuthenticationType: AMAZON_COGNITO_USER_POOLS
      UserPoolConfig:
        AwsRegion: !Ref AWS::Region
        DefaultAction: ALLOW
        UserPoolId: !Ref CognitoUserPool

  AppSyncSchema:
    Type: AWS::AppSync::GraphQLSchema
    Properties:
      ApiId: !GetAtt AppSyncApi.ApiId
      Definition: |
        type Query {
          getHello: String
        }
        schema {
          query: Query
        }

  LambdaFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: cmd/
      Handler: bootstrap
      Runtime: provided.al2
      FunctionName: simple-es-stask-lambda-resolver
      Architectures: [arm64]
      Environment:
        Variables:
          LOG_LEVEL: DEBUG
          PARAM1: VALUE

  AppSyncLambdaDataSource:
    Type: AWS::AppSync::DataSource
    Properties:
      ApiId: !GetAtt AppSyncApi.ApiId
      Name: AppSyncLambdaDataSource
      Type: AWS_LAMBDA
      LambdaConfig:
        LambdaFunctionArn: !GetAtt LambdaFunction.Arn
      ServiceRoleArn: !GetAtt AppSyncLambdaRole.Arn

  AppSyncLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - appsync.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: AppSyncLambdaRolePolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource:
                  - !GetAtt LambdaFunction.Arn

  AppSyncLambdaResolver:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !GetAtt AppSyncApi.ApiId
      TypeName: Query
      FieldName: getHello
      DataSourceName: !GetAtt AppSyncLambdaDataSource.Name

Outputs:
  GraphQLApiUrl:
    Description: The URL of the AppSync API
    Value: !GetAtt AppSyncApi.GraphQLUrl

  UserPoolId:
    Description: The ID of the Cognito User Pool
    Value: !Ref CognitoUserPool

  UserPoolClientId:
    Description: The ID of the Cognito User Pool Client
    Value: !Ref CognitoUserPoolClient